environment:

  matrix:

    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"

build: off

test_script:

  - "%PYTHON%\\python.exe -m pytest --cov-report xml --cov-report term --cov=app unit_tests"
  - "%PYTHON%\\python.exe -m flake8"

after_test:

  - "%PYTHON%\\python.exe -m codecov -f coverage.xml"
