environment:

  matrix:

    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements-dev.txt"

build: off

check_syntax:
  - "%PYTHON%\\python.exe -m flake8"
  - "%PYTHON%\\python.exe -m pylint unit_tests app  --disable=no-member"

test_unit:

  - "%PYTHON%\\python.exe -m pytest --cov-report xml --cov-report term --cov=app -s unit_tests"
  - "%PYTHON%\\python.exe -m codecov -f coverage.xml -F unittests"

test_regression:
  -
  - "%PYTHON%\\python.exe -m pytest --cov-report xml --cov-report term --cov=app -s regression_tests"
  - "%PYTHON%\\python.exe -m codecov -f coverage.xml -F regresiontests"


