environment:

  matrix:

    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install:
  
  - "%PYTHON%\\python.exe build.py reqs"

build: off

test_script:

  - "%PYTHON%\\python.exe build.py quality test"


