name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint
      run: |
        flake8
        pylint unit_tests regression_tests app  --disable=no-member
    - name: Test with pytest
      run: |
        python -m pytest --junitxml results.xml -s unit_tests/*.py regression_tests/*.py
